name: Build GoMuscu iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.86.4

      - name: Vérifier Xcode
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Construire GoMuscu
        run: |
          flet build ipa --no-rich-output

      - name: Récupérer l'IPA
        uses: actions/upload-artifact@v4
        with:
          name: GoMuscu-iOS
          path: "**/*.ipa"
